carousel:
    images: carousel2.jpg, carousel10.jpg, carousel24.jpg, carousel22.jpg, carousel23.jpg,
        carousel1.jpg
    refresh-cron: 0 */5 * * * *
cloudinary:
    api-key: 144334876895965
    api-secret: ${CLOUDINARY_SECRET}
    cloud-name: dmknnra7k
logging:
    level:
        blog: WARN
        org: WARN
        org.hibernate.SQL: DEBUG
server:
    port: 8080
spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: 1234
        url: jdbc:mysql://localhost:3306/lastDB?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
        username: root
    jpa:
        hibernate:
            ddl-auto: create-drop
        open-in-view: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true
    mvc:
        hiddenmethod:
            filter:
                enabled: true
    servlet:
        multipart:
            max-file-size: 1MB
            max-request-size: 5MB
